version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digital-wallet
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
    container_name: fastapi-app
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/digital-wallet
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: