name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - pipeline
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Setup Docker Compose
        run: |
          # Instalar docker-compose se necessário
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: make build

      - name: Start services
        run: make up

      - name: Wait for services to be ready
        run: |
          until docker compose exec -T db pg_isready -U postgres; do
            echo "Waiting for database..."
            sleep 5
          done

      - name: Install dependencies
        run: |
          # Para ambientes CI/CD
          if [ -n "$CI" ]; then
            docker-compose exec -T web pip install -r requirements-dev.txt || docker compose exec -T web pip install -r requirements-dev.txt
          else
            make requirements
          fi

      - name: Run migrations
        run: make migrate

      - name: Run tests with coverage
        run: make test-coverage

      - name: Generate coverage badge
        run: |
          pip install coverage-badge
          coverage-badge -o coverage.svg -f

      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage.svg
