name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - pipeline
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Start services
        run: |
          make build
          make up -d

      - name: Wait for healthchecks (DB and Web)
        run: |
          echo "Aguardando containers ficarem saudáveis..."
          for i in {1..10}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' $(docker compose ps -q db))
            echo "DB status: $STATUS"
            [ "$STATUS" == "healthy" ] && break
            sleep 5
          done

          for i in {1..10}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' $(docker compose ps -q web))
            echo "Web status: $STATUS"
            [ "$STATUS" == "healthy" ] && break
            sleep 5
          done

      - name: Install Python dev dependencies
        run: |
          docker compose exec -T web pip install -r requirements-dev.txt

      - name: Run migrations
        run: |
          docker compose exec -T web alembic upgrade head

      - name: Create coverage directory and set permissions
        run: |
          docker compose exec -T --user=root web mkdir -p tmp/coverage && \
          docker compose exec -T --user=root web chmod -R 777 tmp/coverage && \
          docker compose exec -T --user=root web chmod -R 777 /home/fastapiuser/app

      - name: Run tests with coverage
        run: |
          docker compose exec -T web pytest --cov=. --cov-report=xml --cov-config=.coveragerc
          docker compose exec -T web mv coverage.xml tmp/coverage/coverage.xml

      - name: Generate coverage badge inside container
        run: |
          docker compose exec -T web pip install coverage-badge
          docker compose exec -T web coverage-badge -o tmp/coverage/coverage.svg -f
          
      - name: Copy coverage report
        run: |
          docker cp $(docker compose ps -q web):/home/fastapiuser/app/tmp/coverage/coverage.svg ./coverage.svg


      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage.svg


  coverage-badge:
    runs-on: ubuntu-latest
    needs: ci-pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Commit coverage
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B coverage-badge
          git add coverage.svg
          git commit -m "chore: update coverage badge"
          git push origin coverage-badge -f
